-- Insert Outfits
INSERT INTO clothing_items (name, price, image_url, description, sizes, category_id) VALUES
  ('Batman Outfit', 49.99, 'outfits/batman.jpg', 'Dress like the Dark Knight.', ARRAY['S','M','L','XL'], (SELECT id FROM categories WHERE name='outfits')),
  ('Business Outfit', 79.99, 'outfits/business.jpg', 'Professional attire for any meeting.', ARRAY['XS','S','M','L','XL'], (SELECT id FROM categories WHERE name='outfits')),
  ('Construction Outfit', 39.99, 'outfits/construction.jpg', 'Durable gear for heavy-duty work.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Indian Attire (Male)', 59.99, 'outfits/indian-bernard.jpg', 'Traditional attire with a modern twist.', ARRAY['XS','S','M','L','XL'], (SELECT id FROM categories WHERE name='outfits')),
  ('Indian Sari (Female)', 59.99, 'outfits/indian-shihtzu.jpg', 'Elegant outfit for festive occasions.', ARRAY['XS','S'], (SELECT id FROM categories WHERE name='outfits')),
  ('Jacket', 49.99, 'outfits/jacket.jpg', 'Stylish jacket for those cold days.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Kimono (mini)', 69.99, 'outfits/kimono-2.jpg', 'A small kimono for to immerse in style.', ARRAY['XS','S'], (SELECT id FROM categories WHERE name='outfits')),
  ('Kimono', 69.99, 'outfits/kimono.jpg', 'Traditional kimono for special occasions.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Mexican Attire', 59.99, 'outfits/mexican.jpg', 'Vibrant outfit with cultural flair.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Nigerian Attire', 69.99, 'outfits/nigerian.jpg', 'Bold and beautiful traditional wear.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Ninja Outfit', 49.99, 'outfits/ninja.jpg', 'Stealthy outfit for the aspiring ninja.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Ornate Dress', 89.99, 'outfits/ornate-dress.jpg', 'An exquisite dress for elegant events.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Yellow Raincoat', 39.99, 'outfits/raincoat-2.jpg', 'Keep dry with style.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Green Raincoat', 39.99, 'outfits/raincoat.jpg', 'Functional raincoat for wet weather.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Smart Outfit', 79.99, 'outfits/smart-2.jpg', 'Chic outfit for smart casual occasions.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Business-Smart Outfit', 79.99, 'outfits/smart-3.jpg', 'Versatile outfit for both work and play.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Dapper Outfit', 79.99, 'outfits/smart-4.jpg', 'Sophisticated style for modern professionals.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Elegant Outfit', 79.99, 'outfits/smart-5.jpg', 'For that Ned Flanders look.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Business-Dog outfit', 79.99, 'outfits/smart-6.jpg', 'Classy outfit for any work event.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Snappy Set', 79.99, 'outfits/smart-7.jpg', 'Stylish outfit for the modern gentleman.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Party Outfit Set', 89.99, 'outfits/smart-party.jpg', 'Cost-effective for the whole litter.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Sophisticated Outfit', 79.99, 'outfits/smart.jpg', 'The quintessential sophisticated attire.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Sporty Set', 49.99, 'outfits/sporty.jpg', 'Comfortable and stylish for active days.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Sundress', 39.99, 'outfits/sundress.jpg', 'Light and breezy for summer outings.', NULL, (SELECT id FROM categories WHERE name='outfits')),
  ('Urban Outfit', 59.99, 'outfits/urban.jpg', 'Chic urban attire for the city dweller.', NULL, (SELECT id FROM categories WHERE name='outfits'));
