-- Insert Outfits
INSERT INTO clothing_items (name, price, image_url, description, sizes, category_id) VALUES
  ('Batman Outfit', 49.99, 'path/to/batman.jpg', 'Dress like the Dark Knight.', ARRAY['S','M','L','XL'], (SELECT id FROM categories WHERE name='Outfits')),
  ('Business Outfit', 79.99, 'path/to/business.jpg', 'Professional attire for any meeting.', ARRAY['XS','S','M','L','XL'], (SELECT id FROM categories WHERE name='Outfits')),
  ('Construction Outfit', 39.99, 'path/to/construction.jpg', 'Durable gear for heavy-duty work.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Indian Attire (Male)', 59.99, 'path/to/indianbernard.jpg', 'Traditional attire with a modern twist.', ARRAY['XS','S','M','L','XL'], (SELECT id FROM categories WHERE name='Outfits')),
  ('Indian Sari (Female)', 59.99, 'path/to/indianshihtzu.jpg', 'Elegant outfit for festive occasions.', ARRAY['XS','S'], (SELECT id FROM categories WHERE name='Outfits')),
  ('Jacket', 49.99, 'path/to/jacketoutfit.jpg', 'Stylish jacket for those cold days.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Kimono (mini)', 69.99, 'path/to/kimono2.jpg', 'A small kimono for to immerse in style.', ARRAY['XS','S'], (SELECT id FROM categories WHERE name='Outfits')),
  ('Kimono', 69.99, 'path/to/kimono.jpg', 'Traditional kimono for special occasions.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Mexican Attire', 59.99, 'path/to/mexican.jpg', 'Vibrant outfit with cultural flair.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Nigerian Attire', 69.99, 'path/to/nigerian.jpg', 'Bold and beautiful traditional wear.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Ninja Outfit', 49.99, 'path/to/ninja.jpg', 'Stealthy outfit for the aspiring ninja.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Ornate Dress', 89.99, 'path/to/ornatedress.jpg', 'An exquisite dress for elegant events.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Yellow Raincoat', 39.99, 'path/to/raincoat2.jpg', 'Keep dry with style.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Green Raincoat', 39.99, 'path/to/raincoat.jpg', 'Functional raincoat for wet weather.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Smart Outfit', 79.99, 'path/to/smart2.jpg', 'Chic outfit for smart casual occasions.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Business-Smart Outfit', 79.99, 'path/to/smart3.jpg', 'Versatile outfit for both work and play.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Dapper Outfit', 79.99, 'path/to/smart4.jpg', 'Sophisticated style for modern professionals.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Elegant Outfit', 79.99, 'path/to/smart5.jpg', 'For that Ned Flanders look.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Business-Dog outfit', 79.99, 'path/to/smart6.jpg', 'Classy outfit for any work event.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Snappy Set', 79.99, 'path/to/smart7.jpg', 'Stylish outfit for the modern gentleman.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Party Outfit Set', 89.99, 'path/to/smartparty.jpg', 'Cost-effective for the whole litter.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Sophisticated Outfit', 79.99, 'path/to/smart.jpg', 'The quintessential sophisticated attire.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Sporty Set', 49.99, 'path/to/sporty.jpg', 'Comfortable and stylish for active days.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Sundress', 39.99, 'path/to/sundress.jpg', 'Light and breezy for summer outings.', NULL, (SELECT id FROM categories WHERE name='Outfits')),
  ('Urban Outfit', 59.99, 'path/to/urban.jpg', 'Chic urban attire for the city dweller.', NULL, (SELECT id FROM categories WHERE name='Outfits'));
